/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EditarPerfilRouteImport } from './routes/editar-perfil'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as SaidaRouteImport } from './routes/saida'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ConfiguracoesAmigosRouteImport } from './routes/configuracoes.amigos'
import { Route as ConfiguracoesBloqueadosRouteImport } from './routes/configuracoes.bloqueados'
import { Route as PerfilIndexRouteImport } from './routes/perfil.index'
import { Route as PerfilIdRouteImport } from './routes/perfil.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarPerfilRoute = EditarPerfilRouteImport.update({
  id: '/editar-perfil',
  path: '/editar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const SaidaRoute = SaidaRouteImport.update({
  id: '/saida',
  path: '/saida',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesAmigosRoute = ConfiguracoesAmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesBloqueadosRoute = ConfiguracoesBloqueadosRouteImport.update({
  id: '/bloqueados',
  path: '/bloqueados',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilIdRoute = PerfilIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PerfilRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/editar-perfil': typeof EditarPerfilRoute
  '/eventos': typeof EventosRoute
  '/explorar': typeof ExplorarRoute
  '/feed': typeof FeedRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/saida': typeof SaidaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/configuracoes/amigos': typeof ConfiguracoesAmigosRoute
  '/configuracoes/bloqueados': typeof ConfiguracoesBloqueadosRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/perfil/': typeof PerfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/editar-perfil': typeof EditarPerfilRoute
  '/eventos': typeof EventosRoute
  '/explorar': typeof ExplorarRoute
  '/feed': typeof FeedRoute
  '/notificacoes': typeof NotificacoesRoute
  '/saida': typeof SaidaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/configuracoes/amigos': typeof ConfiguracoesAmigosRoute
  '/configuracoes/bloqueados': typeof ConfiguracoesBloqueadosRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/perfil': typeof PerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/editar-perfil': typeof EditarPerfilRoute
  '/eventos': typeof EventosRoute
  '/explorar': typeof ExplorarRoute
  '/feed': typeof FeedRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/saida': typeof SaidaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/configuracoes/amigos': typeof ConfiguracoesAmigosRoute
  '/configuracoes/bloqueados': typeof ConfiguracoesBloqueadosRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/perfil/': typeof PerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/chat'
    | '/configuracoes'
    | '/editar-perfil'
    | '/eventos'
    | '/explorar'
    | '/feed'
    | '/notificacoes'
    | '/perfil'
    | '/saida'
    | '/sitemap.xml'
    | '/configuracoes/amigos'
    | '/configuracoes/bloqueados'
    | '/perfil/$id'
    | '/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/chat'
    | '/configuracoes'
    | '/editar-perfil'
    | '/eventos'
    | '/explorar'
    | '/feed'
    | '/notificacoes'
    | '/saida'
    | '/sitemap.xml'
    | '/configuracoes/amigos'
    | '/configuracoes/bloqueados'
    | '/perfil/$id'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/chat'
    | '/configuracoes'
    | '/editar-perfil'
    | '/eventos'
    | '/explorar'
    | '/feed'
    | '/notificacoes'
    | '/perfil'
    | '/saida'
    | '/sitemap.xml'
    | '/configuracoes/amigos'
    | '/configuracoes/bloqueados'
    | '/perfil/$id'
    | '/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ChatRoute: typeof ChatRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  EditarPerfilRoute: typeof EditarPerfilRoute
  EventosRoute: typeof EventosRoute
  ExplorarRoute: typeof ExplorarRoute
  FeedRoute: typeof FeedRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  SaidaRoute: typeof SaidaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar-perfil': {
      id: '/editar-perfil'
      path: '/editar-perfil'
      fullPath: '/editar-perfil'
      preLoaderRoute: typeof EditarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saida': {
      id: '/saida'
      path: '/saida'
      fullPath: '/saida'
      preLoaderRoute: typeof SaidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/amigos': {
      id: '/configuracoes/amigos'
      path: '/amigos'
      fullPath: '/configuracoes/amigos'
      preLoaderRoute: typeof ConfiguracoesAmigosRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/bloqueados': {
      id: '/configuracoes/bloqueados'
      path: '/bloqueados'
      fullPath: '/configuracoes/bloqueados'
      preLoaderRoute: typeof ConfiguracoesBloqueadosRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/$id': {
      id: '/perfil/$id'
      path: '/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof PerfilIdRouteImport
      parentRoute: typeof PerfilRoute
    }
  }
}

interface ConfiguracoesRouteChildren {
  ConfiguracoesAmigosRoute: typeof ConfiguracoesAmigosRoute
  ConfiguracoesBloqueadosRoute: typeof ConfiguracoesBloqueadosRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesAmigosRoute: ConfiguracoesAmigosRoute,
  ConfiguracoesBloqueadosRoute: ConfiguracoesBloqueadosRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

interface PerfilRouteChildren {
  PerfilIdRoute: typeof PerfilIdRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilIdRoute: PerfilIdRoute,
  PerfilIndexRoute: PerfilIndexRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ChatRoute: ChatRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  EditarPerfilRoute: EditarPerfilRoute,
  EventosRoute: EventosRoute,
  ExplorarRoute: ExplorarRoute,
  FeedRoute: FeedRoute,
  NotificacoesRoute: NotificacoesRoute,
  PerfilRoute: PerfilRouteWithChildren,
  SaidaRoute: SaidaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
