/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as SaidaRouteImport } from './routes/saida'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedEditarPerfilRouteImport } from './routes/_authenticated/editar-perfil'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as AuthenticatedExplorarRouteImport } from './routes/_authenticated/explorar'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedConfiguracoesAmigosRouteImport } from './routes/_authenticated/configuracoes.amigos'
import { Route as AuthenticatedConfiguracoesBloqueadosRouteImport } from './routes/_authenticated/configuracoes.bloqueados'
import { Route as AuthenticatedPerfilIndexRouteImport } from './routes/_authenticated/perfil.index'
import { Route as AuthenticatedPerfilIdRouteImport } from './routes/_authenticated/perfil.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const SaidaRoute = SaidaRouteImport.update({
  id: '/saida',
  path: '/saida',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditarPerfilRoute =
  AuthenticatedEditarPerfilRouteImport.update({
    id: '/editar-perfil',
    path: '/editar-perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExplorarRoute = AuthenticatedExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesAmigosRoute =
  AuthenticatedConfiguracoesAmigosRouteImport.update({
    id: '/amigos',
    path: '/amigos',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesBloqueadosRoute =
  AuthenticatedConfiguracoesBloqueadosRouteImport.update({
    id: '/bloqueados',
    path: '/bloqueados',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedPerfilIndexRoute =
  AuthenticatedPerfilIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedPerfilIdRoute = AuthenticatedPerfilIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPerfilRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/saida': typeof SaidaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat': typeof AuthenticatedChatRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/editar-perfil': typeof AuthenticatedEditarPerfilRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/explorar': typeof AuthenticatedExplorarRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/configuracoes/amigos': typeof AuthenticatedConfiguracoesAmigosRoute
  '/configuracoes/bloqueados': typeof AuthenticatedConfiguracoesBloqueadosRoute
  '/perfil/$id': typeof AuthenticatedPerfilIdRoute
  '/perfil/': typeof AuthenticatedPerfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/saida': typeof SaidaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat': typeof AuthenticatedChatRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/editar-perfil': typeof AuthenticatedEditarPerfilRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/explorar': typeof AuthenticatedExplorarRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/configuracoes/amigos': typeof AuthenticatedConfiguracoesAmigosRoute
  '/configuracoes/bloqueados': typeof AuthenticatedConfiguracoesBloqueadosRoute
  '/perfil/$id': typeof AuthenticatedPerfilIdRoute
  '/perfil': typeof AuthenticatedPerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/saida': typeof SaidaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/editar-perfil': typeof AuthenticatedEditarPerfilRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/explorar': typeof AuthenticatedExplorarRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/_authenticated/configuracoes/amigos': typeof AuthenticatedConfiguracoesAmigosRoute
  '/_authenticated/configuracoes/bloqueados': typeof AuthenticatedConfiguracoesBloqueadosRoute
  '/_authenticated/perfil/$id': typeof AuthenticatedPerfilIdRoute
  '/_authenticated/perfil/': typeof AuthenticatedPerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/entrar'
    | '/saida'
    | '/sitemap.xml'
    | '/chat'
    | '/configuracoes'
    | '/editar-perfil'
    | '/eventos'
    | '/explorar'
    | '/feed'
    | '/notificacoes'
    | '/perfil'
    | '/configuracoes/amigos'
    | '/configuracoes/bloqueados'
    | '/perfil/$id'
    | '/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/entrar'
    | '/saida'
    | '/sitemap.xml'
    | '/chat'
    | '/configuracoes'
    | '/editar-perfil'
    | '/eventos'
    | '/explorar'
    | '/feed'
    | '/notificacoes'
    | '/configuracoes/amigos'
    | '/configuracoes/bloqueados'
    | '/perfil/$id'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/entrar'
    | '/saida'
    | '/sitemap.xml'
    | '/_authenticated/chat'
    | '/_authenticated/configuracoes'
    | '/_authenticated/editar-perfil'
    | '/_authenticated/eventos'
    | '/_authenticated/explorar'
    | '/_authenticated/feed'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/configuracoes/amigos'
    | '/_authenticated/configuracoes/bloqueados'
    | '/_authenticated/perfil/$id'
    | '/_authenticated/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  SaidaRoute: typeof SaidaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saida': {
      id: '/saida'
      path: '/saida'
      fullPath: '/saida'
      preLoaderRoute: typeof SaidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editar-perfil': {
      id: '/_authenticated/editar-perfil'
      path: '/editar-perfil'
      fullPath: '/editar-perfil'
      preLoaderRoute: typeof AuthenticatedEditarPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explorar': {
      id: '/_authenticated/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof AuthenticatedExplorarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/amigos': {
      id: '/_authenticated/configuracoes/amigos'
      path: '/amigos'
      fullPath: '/configuracoes/amigos'
      preLoaderRoute: typeof AuthenticatedConfiguracoesAmigosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/bloqueados': {
      id: '/_authenticated/configuracoes/bloqueados'
      path: '/bloqueados'
      fullPath: '/configuracoes/bloqueados'
      preLoaderRoute: typeof AuthenticatedConfiguracoesBloqueadosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/perfil/': {
      id: '/_authenticated/perfil/'
      path: '/'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AuthenticatedPerfilIndexRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/perfil/$id': {
      id: '/_authenticated/perfil/$id'
      path: '/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof AuthenticatedPerfilIdRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
  }
}

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesAmigosRoute: typeof AuthenticatedConfiguracoesAmigosRoute
  AuthenticatedConfiguracoesBloqueadosRoute: typeof AuthenticatedConfiguracoesBloqueadosRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesAmigosRoute:
      AuthenticatedConfiguracoesAmigosRoute,
    AuthenticatedConfiguracoesBloqueadosRoute:
      AuthenticatedConfiguracoesBloqueadosRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedPerfilRouteChildren {
  AuthenticatedPerfilIdRoute: typeof AuthenticatedPerfilIdRoute
  AuthenticatedPerfilIndexRoute: typeof AuthenticatedPerfilIndexRoute
}

const AuthenticatedPerfilRouteChildren: AuthenticatedPerfilRouteChildren = {
  AuthenticatedPerfilIdRoute: AuthenticatedPerfilIdRoute,
  AuthenticatedPerfilIndexRoute: AuthenticatedPerfilIndexRoute,
}

const AuthenticatedPerfilRouteWithChildren =
  AuthenticatedPerfilRoute._addFileChildren(AuthenticatedPerfilRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedEditarPerfilRoute: typeof AuthenticatedEditarPerfilRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedExplorarRoute: typeof AuthenticatedExplorarRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedEditarPerfilRoute: AuthenticatedEditarPerfilRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedExplorarRoute: AuthenticatedExplorarRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  SaidaRoute: SaidaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
